### ISSUE TITLE
Compatibility issue between section-index plugin and mkdocs-material blog plugin

### ISSUE THREAD

**Issue by capjan** [oprypin/mkdocs-section-index#25]
Hello!

First, thank you for creating and maintaining the fantastic section-index plugin. It has been a great addition to my documentation workflow!

I recently encountered an issue when trying to use the section-index plugin in combination with the mkdocs-material plugin’s blog feature. I’m not sure if this issue should be addressed here or in the mkdocs-material repository, so I’m reporting it here for now.

**Steps to Reproduce**:

1. Create a new MkDocs project.
2. Use the following mkdocs.yml configuration:  
```yaml
site_name: My Docs
theme: material
plugins: 
  - blog
  - section-index
```
3. Run the MkDocs development server using:
```zsh
mkdocs serve
```

**Observed Behavior**:

The build fails with the following error message:

```zsh
(venv) ~/Code/mkdocs-test (main ✘)✖✹✭ ᐅ mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
ERROR   -  Error reading page 'blog/index.md':
Traceback (most recent call last):
  File ".../venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File ".../site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File ".../site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/mkdocs/__main__.py", line 272, in serve_command
    serve.serve(**kwargs)
  File ".../site-packages/mkdocs/commands/serve.py", line 85, in serve
    builder(config)
  File ".../site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, serve_url=None if is_clean else serve_url, dirty=is_dirty)
  File ".../site-packages/mkdocs/commands/build.py", line 310, in build
    _populate_page(file.page, config, files, dirty)
  File ".../site-packages/mkdocs/commands/build.py", line 163, in _populate_page
    page.markdown = config.plugins.on_page_markdown(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/mkdocs/plugins.py", line 635, in on_page_markdown
    return self.run_event('page_markdown', markdown, page=page, config=config, files=files)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/mkdocs/plugins.py", line 566, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/material/plugins/blog/plugin.py", line 241, in on_page_markdown
    assert isinstance(view, View)
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Expected Behavior**:

The build should complete successfully, and the site should render without errors when using both plugins together.

**Environment Details**:

- MkDocs Version: 1.6.1
- Material for MkDocs Version: 9.5.47
- section-index Plugin Version: 0.3.9
- Python Version: 3.12.5
- Operating System: macOS 15.1.1

Additional Notes:

- This issue occurs specifically when the blog plugin is active in the configuration.

Please let me know if I can provide further details or assist with debugging!

**Comment by capjan** [comment]
Closing this as a duplicate of #22
